Serialize Sonar Ping interval.
Regalis11/Barotrauma pull request #11309
Opened 2023-02-22 00:08 UTC by Jade-Harleyy

This PR allows modders to change the interval between active sonar pings.

2023-02-22 05:40 UTC, mygamingaccount commented
The interval should instead depend on the selected distance, no? You can change the strength of the ping, but not the speed at which it travels through the water.

2023-02-22 08:31 UTC, Regalis11 commented
> The interval should instead depend on the selected distance, no? You can change the strength of the ping, but not the speed at which it travels through the water.

The interval just means the interval at which a ping is emitted, not the speed at which the emitted ping travels. There should be no limit to the frequency, nor should it depend on the distance.

2023-02-22 08:36 UTC, Regalis11 requested changes
The speed at which the pings travel is currently relative to the frequency:

`activePings[pingIndex].State += deltaTime * PingFrequency;`

This needs to be changed if the frequency is made editable.

2023-02-22 09:16 UTC, mygamingaccount commented
> The interval just means the interval at which a ping is emitted, not the speed at which the emitted ping travels. There should be no limit to the frequency, nor should it depend on the distance.

Right, but if you reduce the interval between transmissions, that will reduce the range, since when you have two SONAR pings spreading out, then you won't know which one you're getting an echo from on the receiver.

So the range of the active sonar with relation to the interval is `R = 1/2 * c/Δt ` where c is the speed of sound, and Δt is the ping interval

2023-02-22 10:00 UTC, Regalis11 commented
> Right, but if you reduce the interval between transmissions, that will reduce the range, since when you have two SONAR pings spreading out, then you won't know which one you're getting an echo from on the receiver.

Wouldn't this be trivial to work around by emitting pings of slightly different frequencies, so you could deduce which ping it was based on the frequency of the echo?

2023-02-22 13:18 UTC, mygamingaccount commented
> Wouldn't this be trivial to work around by emitting pings of slightly different frequencies, so you could deduce which ping it was based on the frequency of the echo?

Perhaps with wildly different frequencies. The narrower the pulse, the wider its spectrum, so it might interfere with the other ping and its reflections if they are similar.
The book I have on sonars elegantly avoids this question of multiple simultaneous transmissions.

2023-02-23 23:08 UTC, Jade-Harleyy commented
oops

2023-06-14 11:31 UTC, Regalis11 requested changes
Found some more issues (the speed being editable isn't really a major problem, but I think the way the AITarget's sector behaves is). All in all I'm starting to get the feeling this is turning to be such an extensive rewrite, for a feature that seems quite niche, that I'm starting to question whether it's worthwhile to do. If it was only possible to apply a delay between pulses, not freely edit the frequency (which means there can be multiple pings active at a time), I think it'd significantly simplify the logic and only take a handful of changes.

2023-06-14 11:31 UTC, Regalis11 commented on Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/Sonar.cs
> +        }
Imo it doesn't make sense for this to be editable, the pings should travel at a fixed speed (realistically should be the speed of sound, even though it's actually much slower in-game).

2023-06-14 11:31 UTC, Regalis11 commented on Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/Sonar.cs
> +                // TODO: Allow multiple seperated sectors & iterate over each active ping to disallow pinging a sector then moving the ping direction to gain information without aggro'ing enemies.
Unaddressed todo note. Now the sector seems to be based on the latest ping, which could potentially be abused.

2023-10-24 06:56 UTC, Regalis11 commented
We feel like this is a too extensive rewrite (which would be very time-consuming to test and could cause hard-to spot side-effect) to address a very niche issue, so I don't think we'll be accepting the PR in this form. Thank you for your contribution regardless!

2023-10-24 06:56 UTC, closed without merging